org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

loader_version=0.19.3
loom_version=1.16-SNAPSHOT

mod_version=1.2.0
maven_group=net.napsternpt.morebbboathud
archives_base_name=morebbboathud

# Version-specific properties live in versions/<version>/gradle.properties
minecraft_version=[VERSIONED]
yarn_mappings=[VERSIONED]
fabric_api_version=[VERSIONED]
bb_boat_hud_version=[VERSIONED]
cloth_config_version=[VERSIONED]
